[build]
  base = ""
  command = "npm install && npx convex codegen && cd frontend && npm ci && npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_CONVEX_URL = "https://ardent-dog-632.convex.cloud"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  port = 8888
  publish = "frontend/.next"
  functions = "netlify/functions"