/* eslint-disable */
/**
 * Generated Convex API types.
 * This file is generated by the Convex CLI.
 * Do not edit this file manually.
 */

import type {
  ApiFromModules,
  filteredFunctionReference,
  FunctionReference,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericTableInfo,
  OptionalRestArgs,
  PublicHttpAction,
  UnvalidatedFunction,
} from "convex/server";
import type * as userActions from "../userActions";
import type * as accountActions from "../accountActions";
import type * as syncActions from "../syncActions";
import type * as transactionActions from "../transactionActions";
import type * as agentActions from "../agentActions";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage for Convex clients:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 *
 * Usage for the Convex CLI:
 * ```bash
 * npx convex run myModule:myFunction
 * ```
 */
declare const fullApi: ApiFromModules<{
  userActions: typeof userActions;
  accountActions: typeof accountActions;
  syncActions: typeof syncActions;
  transactionActions: typeof transactionActions;
  agentActions: typeof agentActions;
}>;
export declare const api: typeof fullApi;

export declare const internal: typeof fullApi;