/* eslint-disable */
/**
 * Generated Convex API types.
 * This file is generated by the Convex CLI.
 * Do not edit this file manually.
 */

// This file will be generated by Convex - placeholder for now
export interface Api {
  // API definitions will be generated here
}